[".config/alacritty/themes"]
    type = "git-repo"
    url = "https://github.com/alacritty/alacritty-theme"
    refreshPeriod = "168h"
[".config/nvim"]
    type = "git-repo"
    url = "https://github.com/nathan-isaac/kickstart.nvim.git"
    refreshPeriod = "168h"
[".local/share/zinit/zinit.git"]
    type = "git-repo"
    url = "https://github.com/zdharma-continuum/zinit.git"
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "git-repo"
    url = "https://github.com/tmux-plugins/tpm"
    refreshPeriod = "168h"
