[general]
import = ["~/.config/alacritty/themes/challenger_deep.yaml"]
live_config_reload = true

[window]
option_as_alt = "Both"
padding = { x = 6, y = 4 }
startup_mode = "Maximized"

[font]
size = 16

[font.bold]
family = "IBM Plex Mono"
style = "Bold"

[font.bold_italic]
family = "IBM Plex Mono"
style = "Bold Italic"

[font.italic]
family = "IBM Plex Mono"
style = "Italic"

[font.normal]
family = "IBM Plex Mono"
style = "Regular"
